### ISSUE TITLE
Running app in iTerm with Solarized Light color scheme produces hard to see log info

### ISSUE THREAD

**Issue by kare** [go-aah/aah#108]
![iterm-light-colors-aah](https://user-images.githubusercontent.com/68578/30038314-b9c45176-91cb-11e7-8ea7-526dc36f1b77.png)

As a side note: Is possible to turn off all colored output? Through configuration preferably. Some people (like me) don't think that colored output makes the output more readable so I'd like to have it off completely.

**Comment by jeevatkm** [comment]
@kare I understand. Currently colored output is not configurable.  I will provide config option in `aah.project` in the upcoming release.

Keep your inputs coming, I will improve it. Thank you.

**Comment by jeevatkm** [comment]
It's done, coming in v0.9 release. Thanks.

**Comment by jeevatkm** [comment]
@kare `v0.9` released with disable color logging option. Give it try and share your feedback.
