### ISSUE TITLE
Add scrypt and pbkdf2 password encoder in module security

### ISSUE THREAD

**Issue by jeevatkm** [go-aah/aah#110]
Currently `aah` supports `bcrypt` password encoder. 

Add `scrypt` and  `pbkdf2` too with configurable options. 

Enhance interface `acrypto.PasswordEncoder` to support `Generate` password hash by algorithm.

```go
type PasswordEncoder interface {
	Generate(password []byte) ([]byte, error)
	Compare(hash, password []byte) bool
}
``` 

- [x] Implement scrypt
- [x] Implement pdkdf2
- [x] Expose convince access of all three algorithm
      - `security.Bcrypt.*`
      - `security.Scrypt.*`
      - `security.Pbkdf2.*`
- [x] CLI update on `aah new` command get password algorithm
- [x] App Template update
- [x] Documentation

**Comment by julienkosinski** [comment]
@jeevatkm Great job! :)
It seems that these days, PBKDF should be avoided... Maybe could be important to advise for scrypt and bcrypt...?
https://medium.com/@mpreziuso/password-hashing-pbkdf2-scrypt-bcrypt-1ef4bb9c19b3
https://security.stackexchange.com/questions/133239/what-is-the-specific-reason-to-prefer-bcrypt-or-pbkdf2-over-sha256-crypt-in-pass

**Comment by jeevatkm** [comment]
Thank you @julienkosinski.

Default password encoder enabled in aah is `bcrypt` with cost 12. Also supports `scrypt` and `pdkdf2` comes with default values to start with. There on user can tune those parameters as per their compliance requirements. 

I believe those post/article discussing about SHA256-crypt, SHA512-crypt vs bcrypt, pbkdf2 hashes.
Good read about password hashes https://security.stackexchange.com/questions/4781/do-any-security-experts-recommend-bcrypt-for-password-storage/

Things should be avoided; just hash (md5, SHA-*), just hash with salt (md5, SHA-*).

Typically its recommended to use `bcrypt`, `scrypt` or  `pbkdf2` (with HMAC-SHA256 or HMAC-SHA512). These algorithms supported by `aah`. So that aah user can choose by their choice.

**Comment by julienkosinski** [comment]
@jeevatkm You do take care of aah users very well! Great link thanks! You're right! :D

**Comment by jeevatkm** [comment]
@julienkosinski Thank you. 

For every feature and enhancement in aah I do lot of study and research for the implementation and default values to align with real world usage. 

Also I just read your updated comment info. I will add warning message via logging if user choose pbkdf2 with non SHA-512 hash. 

Do you mind reviewing this doc https://github.com/go-aah/docs/blob/v0.9-dev/password-encoders.md and add you inputs in it?

**Comment by julienkosinski** [comment]
@jeevatkm Yeah, gonna propose some words about it. SHA-1 collision attacks are not that severe as I wrote in my first edit. Maybe gonna propose something in the doc to advise to avoid SHA-1 anyway :).

Recent Google searches : http://thehackernews.com/2017/02/sha1-collision-attack.html
https://crypto.stackexchange.com/questions/15218/is-pbkdf2-hmac-sha1-really-broken
