### ISSUE TITLE
502 error with virtual machine and forwarded port on Hot-reload server

### ISSUE THREAD

**Issue by julienkosinski** [go-aah/aah#120]
Hello,

When we execute aah service behind a virtual machine running a linux distribution with the 8080 port forwarded.
When hot-reload is executed, first request trigger a 502 error, second one does work correctly.

I do know you're aware of it @jeevatkm, it's just to keep track on that :).
Thank you very much! :D

**Comment by jeevatkm** [comment]
I'm documenting here so that aah users will know insights into issue. This behavior is happening in aah hot-reload server `not` the release version.

**Comment by jeevatkm** [comment]
Fixed :) releasing with v0.9
