### ISSUE TITLE
aah: Choosing Features, Enhancements for v0.10 :)

### ISSUE THREAD

**Issue by jeevatkm** [go-aah/aah#127]
Hello aah users - 

I'm happy to mention `v0.9` development is completed. Will work on documentation, tutorials and website updates. Once done I will make a `v0.9` release.

----

As you know `aah` development is community driven; based on community votes I will priorities the features, enhancements from roadmap.

Please have a look on [Open Issues](https://github.com/go-aah/aah/issues) and [Roadmap](https://github.com/go-aah/aah/projects); provide your inputs.

Thank you 😃

**Comment by julienkosinski** [comment]
Thank you very much! :-)

For me the top 3 features I'd really like to have is as below! :-)

1. CORS
2. Validators
3. Dockerize

Test suite is the fourth for me :-).

Thanks again!

**Comment by blagodus** [comment]
Thank you for asking,at least some of these:
- Validation
- I see this in roadmap: 
    `Out-of-the-box third party custom template engine support (amber, pongo2, Jade)`
I suggest Out-of-the-box [Jet template engine](github.com/CloudyKit/jet) support, please look at features and tell  me what you think?
- aah migrate #116, aah switch #113 and aah update #114 
- TestSuite for integration and functional test case. #22 
- Add option to Auto generate Docker file

How to pronounse aah and what it means? Add this answer to website..

**Comment by jeevatkm** [comment]
@julienkosinski @blagodus Thank you for your inputs.

I have added aah pronounce and meaning in website footer. Also `aah switch` cmd is released in v0.9 

I will pick following items for v0.10 iteration:
* Validation
* CORS
* Config Reload via SIGHUB signal
* Starting `aah generate` cmd with docker and systemd file then I will bring other items like controller, view, i18n, etc.
* `aah update` cmd

Once above items done then If time permits I will pick:
* TestSuite
* Few ready to use pluggable auth schemes
* Few ready to use pluggable view engines

@blagodus Jet template engine looks good, I'm adding into roadmap. Thanks.

I hope this balance outs v0.10 😄

**Comment by jeevatkm** [comment]
Starting v0.10 iteration :)

**Comment by julienkosinski** [comment]
@jeevatkm Perfect!! Thank you! :D
