### ISSUE TITLE
Question: Custom password encoder

### ISSUE THREAD

**Issue by Raggaer** [go-aah/aah#128]
So reading the `aahframework.org/security.v0/acrypto` I guess you cant declare a custom password encoder right now?

How I am supposed to use the `form` auth type with a custom password encoder?

Thanks

**Comment by jeevatkm** [comment]
@Raggaer Yes, you're correct. Custom password encoder feature coming in `v0.9` release. Work-in-progress documentation of password encoder https://github.com/go-aah/docs/blob/v0.9-dev/password-encoders.md

**Comment by jeevatkm** [comment]
I'm closing it.

**Comment by jeevatkm** [comment]
@Raggaer `v0.9` has been released today. Now you can add custom password encoder.
