### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by jeevatkm** [go-aah/aah#132]
My homework and discussion with aah users in the thread then finally chosen `https://github.com/go-playground/validator` as a Validator library for aah framework. 

**Will add method details and types later on**

On **Validation errors**, aah will call error handler in the sequence of -

* Controller level error handler (coming in `v0.10`)
* Centralized error handler
* Default error handler

----

As we know currently aah has [Centralized Error Handling](http://docs.aahframework.org/centralized-error-handler.html) feature. 

As part of **_flexible validator feature_**, I'm planning take `aah` capabilities to the next level via providing an optional controller level `ErrorHandler`. This is gonna have small breaking change, what it means-
* Existing `aah.ErrorHandler` func type would be refactored to `aah.ErrorHandlerFunc`
* New `aah.ErrorHandler` interface comes in.

So aah framework user has an option handle **errors** at controller level too-

```go
type StoryController struct {
  *aah.Context
}

// HandleError method to handle errors for Story controller
func (*s StoryController) HandleError(e *aah.Error) bool {
  // All story controller errors sent to this method
  //   - Return ture, if you have handled an errors
  //   - Return false, aah will propagate the error to centralized error handler
}
``` 

----

- [x] Implementation 
- [x] Documentation

**Comment by broklyngagah** [comment]
Hi @jeevatkm 
Any plan to use or integrate with existing library ?
I suggest gopkg.in/go-playground/validator.v9 

Thanks :blush:

**Comment by jeevatkm** [comment]
@broklyngagah Yes, I'm planning to use flexible library(need to do my homework on it). I haven't made any choices so far. Thanks for the suggesting one. I will look into it.

**Comment by jeevatkm** [comment]
@broklyngagah @Eraac I have done my homework on following validation libraries.

* https://github.com/go-playground/validator
* https://github.com/asaskevich/govalidator

I feel like second one is more flexible/extensible, what do you think of it?

Looking forward to your inputs.

**Comment by jeevatkm** [comment]
@broklyngagah @Eraac After your inputs we can pick one library for integrating with aah framework.

**Comment by broklyngagah** [comment]
Hi @jeevatkm 
Thanks for mentioning me. To be honest i have not use the second one. in my opinion for [this package](https://github.com/go-playground/validator), it's easy to integrate and this package support for custom error message that you can integrate with multiple language. But it's up to you, i believe that both package is good enough for validation. :) How about you @eraac ?

**Comment by Eraac** [comment]
same here, i have already using go-playground/validator, it seems more simple to implement/use but maybe with less builtin validator. i18n **and** l10n is a real plus.

For me asaskevich/govalidator is probably more complete (for custom validation), but more complex too

**Comment by jeevatkm** [comment]
@broklyngagah @Eraac Thank you for your inputs. Let's keep it simple 😄 

I will use https://github.com/go-playground/validator as a Validator for aah.

---

Also I have added the spec info above. Please have a look and let me know.

**Comment by jeevatkm** [comment]
Unpublished doc: https://github.com/go-aah/docs/blob/v0.10-edge/validation.md
