### ISSUE TITLE
Use parent path and controller in child nodes (routes.conf)

### ISSUE THREAD

**Issue by azbshiri** [go-aah/aah#137]
Hey, I was looking through your framework and I really liked it. Is it possible to do this? or any other better ways to remove duplication.

**Expected:**
```
domains {
  localhost {
    name = "new routes"
    host = "localhost"
    redirect_trailing_slash = true
    method_not_allowed = true
    auto_options = true
    routes {
      baskets {
        path = "/baskets"
        controller = "BasketController"
        auth = "anonymous"
        index {
          action = "Index"
        }
        create {
          action = "Create"
        }
      }
    }
  }
}
```

**Can Do: (It works now but not DRY)**
```
domains {
  localhost {
    name = "new routes"
    host = "localhost"
    redirect_trailing_slash = true
    method_not_allowed = true
    auto_options = true
    routes {
      baskets {
        path = "/baskets"
        routes {
          show_basket {
            path = "/"
            controller = "BasketController"
            action = "Index"
            auth = "anonymous"
          }
          create_basket {
            path = "/"
            method = "POST"
            controller = "BasketController"
            action = "Create"
          }
        }
      }
    }
  }
}
```

**Actual:**
```
domains {
  localhost {
    name = "new routes"
    host = "localhost"
    redirect_trailing_slash = true
    method_not_allowed = true
    auto_options = true
    routes {
      v1 {
        path = "/v1/"
        routes {
          baskets {
            path = "/baskets"
            controller = "BasketController"
            action = "Index"
            auth = "anonymous"
          }
          create_basket {
            path = "/baskets"
            method = "POST"
            controller = "BasketController"
            action = "Create"
          }
        }
      }
    }
  }
}

```

**Comment by jeevatkm** [comment]
@azbshiri I'm glad to hear, you liked aah framework.

Nested routes config works like this:
```
routes {
  <route_name1> {
    # this route attributes

    # child routes - level 1
    routes {
      <route_name11> {
        # this route attributes

        # child routes - level 2
        routes {
          <route_name111> {

            # you can go on any level with your creativity
            
          }        
        }
      }
    }
  }

  <route_name2> {
    # same as above
  }
}
```

* path - inherits the parent path as prefix to child path
* method - have to be provided otherwise `GET` is chosen
* controller - have to be provided for every routes
* action - if not provided then value is chosen based on HTTP method value
* auth - value is inherited from parent as-is if not provided in the child route
* max_body_size - if not provided then `request.max_body_size` config value from `aah.conf`
* anti_csrf_check - default is true for web application, for REST API this doesn't take effect even if its defined 

----

While composing this answer, I thought below enhancement:

* inherit `controller` value if not provided in the child route (will add this enhancement in the `v0.10` release)

Feel free suggest and recommend improvements to routes config and any area in the aah.

**Comment by jeevatkm** [comment]
@azbshiri I have described above, how its currently processing the `routes.conf`.

Can you propose the improve the improvements on`routes.conf`? Routes processing code is [here](https://github.com/go-aah/router/blob/v0-unstable/router.go#L621).

I'm looking forward to your inputs and contributions.

**Comment by jeevatkm** [comment]
Also I will add following enhancement too. `route name` is plays key role, it must be provide.

* path - if its not provided in child route inherit parent use as-is.

With `v0.10` release onwards you can do:

Your second example will turn into:
```
routes {
  baskets {
    path = "/baskets"
    controller = "BasketController"
    routes {
      show_basket {
        action = "Index" # it can be ignored, since default HTTP method value is `GET` and for that action name is `Index`
        auth = "anonymous"
      }
      create_basket {
        method = "POST"
        action = "Create" # it can be ignored, since action name`Create` is mapped to POST
      }
    }
  }
}
```

**Comment by jeevatkm** [comment]
@azbshiri I have just added these two enhancements. Its available on aah edge version, you can give it try and share your feedback.

* path - if its not provided in child route inherit parent use as-is.
* controller - if its not provided in the child route inherit parent use as-is.

Once you installed aah version `v0.9` then you can execute `aah switch` command to try out `v0.10`edge version.

Now routes config become (your second example from the question):
```
routes {
  baskets {
    path = "/baskets"
    controller = "BasketController"
    routes {
      show_basket {
        auth = "anonymous"
      }
      create_basket {
        method = "POST"
      }
    }
  }
}
```

**Comment by azbshiri** [comment]
Thanks for your attention and fast response. I'll check that and let you know.
