### ISSUE TITLE
Unmarshaling JSON to struct and vice versa are slow

### ISSUE THREAD

**Issue by azbshiri** [go-aah/aah#138]
When I POST a JSON document it takes almost 2ms to unmarshal and vice versa. I think it has something to do with JSON pool maybe but I'll try to profile it.

**Comment by jeevatkm** [comment]
@azbshiri Typically it should not take that much. Sure every input is helpful to improve aah. Let me know.

**Comment by jeevatkm** [comment]
I believe you're auto parse and bind feature. Keep me posted.

**Comment by azbshiri** [comment]
@jeevatkm What do you mean by auto parse?

**Comment by jeevatkm** [comment]
@azbshiri You're using auto parse and bind feature, documentation is here https://docs.aahframework.org/request-parameters-auto-bind.html

Typically it should take same execution time as when you do manually parse the request body. Like below:

```go
func (b *BasketController) Create() {
  var basket models.Basket
  if err := json.NewDecoder(b.Req.Body()).Decode(&basket); err != nil {
    b.Reply().BadRequest().JSON(aah.Data{
      "error": "unable to read request body",
    })
    return
  }
  
  b.Reply().Ok().JSON(basket)
}
```

BTW, you no need to use `Status(200)` when you're using `Ok()`, documentation: https://docs.aahframework.org/reply.html

----

Keep me posted on your finding, If anything I will quickly address and will improve it.

**Comment by jeevatkm** [comment]
@azbshiri I'm closing it for now. Once you find the reproducible steps of the issue, please let me know then I will looking into it. Thanks.
