### ISSUE TITLE
Using jade template engine example?

### ISSUE THREAD

**Issue by hengestone** [go-aah/aah#139]
Until pluggable template view engines are added, can someone add an example on how to use an external template engine like `jade`?

From the documentation it seems like it should be simple, but I'm new to golang, so help appreciated! :)

Thanks

**Comment by jeevatkm** [comment]
@hengestone Thank you for your interest in aah. I'm actively working on `v0.10` features and enhancements, currently my hands are full. I could add Jade pluggable option and tutorial example along with `v0.10` release.

**Comment by jeevatkm** [comment]
@hengestone Thank you for your patience. I'm planning to create a pluggable view engine of `Jade` as part of `v0.10` release. 

I would like to confirm; which library you're referring to?

* Is it this one? https://github.com/Joker/jade

**Comment by hengestone** [comment]
Yes, that seems to be the most popular/stable library for jade (or now pug) templates.
Thanks!

**Comment by jeevatkm** [comment]
@hengestone Thank you 😄

**Comment by jeevatkm** [comment]
@hengestone FYI, I have given try examples and submitted issues at Jade/Pug repository Joker/Jade#18 and Joker/Jade#19.

Please have a look. Am I understood correctly?

**Comment by jeevatkm** [comment]
@hengestone I have a good news for you. Pug view engine (https://github.com/aah-cb/ve-pug) is ready to use on aah edge version. Thank you for your patience.

Please use command `aah switch` to get edge version and you could create new project with pug view engine using command `aah new`.
