### ISSUE TITLE
getting started

### ISSUE THREAD

**Issue by MikhailKlemin** [go-aah/aah#140]
I have that problem that if you fed absolute path to the  `aah new` command like `/home/mike/whatever/aah-first-app` it would say no error and wrote that aah-first-app   was created successfully, but there will be nothing in the folder.

**Comment by jeevatkm** [comment]
@MikhailKlemin `aah new` supports only import path as an input. Typically aah project gets created under `GOPATH`. I believe your project could be under your `GOPATH`.

You can easily know about absolute project path. Just look for string `Your aah web application was created successfully at '.....'` from `aah new` output.

Please let me know, thanks.

**Comment by MikhailKlemin** [comment]
Yes, you  are right I missed :-( It created in GOPATH that whole thing like `$GOPATH//home/mike/whatever/aah-first-app"

**Comment by jeevatkm** [comment]
@MikhailKlemin Do you see this `$GOPATH` as-is in the output? if yes then I believe you have not yet setup your `GOPATH`.

**Comment by MikhailKlemin** [comment]
Hi, I am sorry there is misunderstanding. I supplied the absolute path and it worked as it should it's just created the whole path starting from my $GOPATH I just was no expecting that. 
Say my $GOPATH is `/home/mike/whatever` and when I supplied to `ahh new`  `/home/mike/whatever/aah-first-app` it created project at `/home/mike/whatever/src/home/mike/whatever/aah-first-app`
I was just lost a little bit, and it was late... Close this one please..

**Comment by jeevatkm** [comment]
Thank you @MikhailKlemin for clarifying it. Please feel free to reach out for any doubts.
