### ISSUE TITLE
Database Migration is Missing

### ISSUE THREAD

**Issue by vzool** [go-aah/aah#150]
Hi,

I browsed many frameworks in order to find something very logical to me, and I found this one.
But, it does not have any migration way to a database.
Do you have a any plans to make something similar to [pop](https://github.com/gobuffalo/pop)?

Thanks

**Comment by adelowo** [comment]
I would argue @jeevatkm wouldn't be interested in something like this as there are tools that have this well done already... see [goose](https://github.com/pressly/goose) for instance

**Comment by jeevatkm** [comment]
@vzool Thank you for your interest in aah framework. Currently aah doesn't have built-in data layer, its an upcoming part in the roadmap. When it comes; it would be easy to use and flexible.

However currently it doesn't stop you from using any data layer library.

@adelowo has a good point about database migration. In my experience, its best to keep database migration activity outside the application as a tool. When I work on data module, will do my homework and provide as much as balanced data layer in aah.

Thanks again. I believe aah is helpful for your app development.

**Comment by moos3** [comment]
I'd like to see something like gorm or some type of orm. That would make this framework killer.

**Comment by jeevatkm** [comment]
@moos3 Thank you for your input. I'm glad to hear that.

I have just started the thread for v0.11.0 #155 😄

**Comment by jeevatkm** [comment]
Closing it, feature selection thread have been started at #155.
