### ISSUE TITLE
aah: Choosing Features and Enhancements for v0.11.0

### ISSUE THREAD

**Issue by jeevatkm** [go-aah/aah#155]
Hello aah users - 

As you know `v0.10` got released on Mar 28, 2018 with new features and enhancements. Also newly designed website, documentation presentation and per version documentation search.

I hope you're liking it 😄  Thank you for your support.

--- 

**Let's move on to next phase of development iteration focusing on `v0.11.0`**

As you know `aah` development is community driven; based on community votes, suggestion and recommendation. I would priorities it. Looking forward to your inputs.

For `v0.11.0` following is my wish list- 

* ORM (Data access layer)
* Configurable option of roles and permissions for each route.
* Make aah anatomy configurable #152 
* Add `aah generate i18n` command to generate i18n vars #119 
* Websocket #126 

Please have a look on [Open Issues](https://github.com/go-aah/aah/issues), [Roadmap](https://github.com/go-aah/aah/projects) or new item from your need; provide your wish list or vote on my wish list.

Then finally balanced wish list would be created. Thank you 😃

**Comment by pharrisee** [comment]
Have a few work projects that I would love to use Aah for, but the lack of a few features is holding me back, namely:

Websockets
SSE
Something like https://github.com/gobuffalo/packr for bundling resources
Simple database layer, not necessarily ORM.  Something like sqlx integration would be awesome.

**Comment by jeevatkm** [comment]
@pharrisee thank you for your inputs. I'm sorry to hear that its holding you.

I would like to clarify the second point - what is the expected feature? I have looked at the packr library; it converts files into binary data then compiles to binary.

**Comment by pharrisee** [comment]
Well, at the moment the packaging done by the aah cli is to create a zip file.  It would be really good if the packaging built  an executable which contained everything required to run the app, no external files.  I can see a few issues with things like config etc, but I'm sure that should be do-able.

**Comment by jeevatkm** [comment]
Actually packing everything into binary is doable, no issues 😄 I will make this feature as on-demand.

* `config` - since aah has feature to accept config file as param so no issues. DevOps team can utilize that without engineering team effort
* `views, css, js, images` - DevOps team looses a capability to modify/update, they have to depend on engineering team. I guess I leave that choice to engineering team

How about startup files? As you know aah does provide startup files (.sh, .cmd).

**Comment by pharrisee** [comment]
I suppose that the startup files would be more necessary with the zipped version than the packed executable?  Also packaging gives a different deployment mechanism which may actually be more in line with some environments.

**Comment by jeevatkm** [comment]
Okay, I guess its decided. 

* Zip archive packing would contain startup files
* Single binary packing is just one binary 

Thank you, could you please create an issue for this feature?

**Comment by pharrisee** [comment]
will do :)

**Comment by blagodus** [comment]
- ORM (Data access layer)
- Configurable option of roles and permissions for each route.
- Websockets

**Comment by jeevatkm** [comment]
Thank you @pharrisee @blagodus for your inputs and votes. 

Main focus for `v0.11.0` release:

* Code and flow optimization #157 
* Data access layer #161
* Binary resource packing #156 
* Websockets #126 
* Configurable option of roles and permissions for each route #162
