### ISSUE TITLE
Binary resource packaging

### ISSUE THREAD

**Issue by pharrisee** [go-aah/aah#156]
Can there be an option at build time to package resources (views, css,js,img and config) into the executable for easy one file deployment?

There are numerous packaging libraries/applications available:

- https://github.com/gobuffalo/packr
- https://github.com/GeertJohan/go.rice
- https://github.com/go-bindata/go-bindata

to name but a few.

---

Updates:

- [x] Feature implemented, available on edge - command is `aah build --single` or `aah b -s`
- [ ] Documentation

**Comment by vzool** [comment]
This is really hot, anything will be already loaded and fetched directly from RAM.
Applications will behave so fast, we just touch SSD/HDD to write to Database.
Facebook working for many years to reach this goal, this is great stuff.

**Comment by pharrisee** [comment]
Not sure if this helps, but this guy has done a fair bit of research and comparison of various resource embedding methods for Go:

http://tech.townsourced.com/post/embedding-static-files-in-go/

**Comment by jeevatkm** [comment]
@pharrisee Thank you, sure I will read it. I'm currently doing my homework; every input helps to shape an idea.

**Comment by jeevatkm** [comment]
@pharrisee Given post is really helpful, he has done quite analysis on this topic. I'm gonna a gather plus points from overall and draw a direction for aah.

Will make good start point for aah single binary goal.

**Comment by jeevatkm** [comment]
Updates:

- [ ] Feature implemented, available on edge - command is `aah build --single` or `aah b -s`
- [ ] Documentation

**Comment by pharrisee** [comment]
1. switched to edge version of AAH and created a new project
2. edited aah.project to get dependencies
3. ran project with 'aah r'
4. get message 'FATAL aah.conf: read \app\config\security.conf: mount does not exist'

Any ideas?

**Comment by jeevatkm** [comment]
@pharrisee Interesting. aah VFS is path separator is always forward slash `/`. I will verify it with windows OS and get back to you. Thanks.

**Comment by pharrisee** [comment]
OK, updated to new release with 'aah s -r' had error:

`FATAL Unable to refresh dependencies:
# aahframework.org/aah.v0
..\..\aahframework.org\aah.v0\aah.go:278:16: a.VFS().IsEmbeddedMode undefined (type *vfs.VFS has no field or method IsEmbeddedMode)
..\..\aahframework.org\aah.v0\aah.go:282:9: a.VFS().SetEmbeddedMode undefined (type *vfs.VFS has no field or method SetEmbeddedMode)`

removed all of the {src,pkg}/aahframework.org directories, and the bin/aah.exe and did another install

ran 'aah s' and get the same error.

**Comment by jeevatkm** [comment]
@pharrisee I'm really sorry. I have committed `aahframework.org/vfs.v0` but missed to tag the prerelease version before commenting here.

Just did it. Please try again.

**Comment by pharrisee** [comment]
OK, did a complete cleanup and reinstalled, switched to edge and get:

````
FATAL Unable to refresh library: tools.v0
````

**Comment by jeevatkm** [comment]
Just now docker build got successfully completed the aah edge version.

https://hub.docker.com/r/aahframework/aah/builds/br68v54j4p9cxr9sski7fcu/

aah cli executes git cmd internally; it may be the interim git issue. 

I am going to verify the edge version build on fresh VM.

**Comment by jeevatkm** [comment]
🎉 I am very glad to hear your feedback. Thank you.

**Comment by pharrisee** [comment]
you are very welcome, and thank you for your work on these features, will make it so much easier to get it adopted at my work place.  

Just FYI I work in a major UK university (I'm the web architect) and will be doing my damndest to introduce Aah there on a major new project.  If I manage it I'll be writing up the experience at a later date.  If you're interested in the results I can let you know how it goes.

**Comment by jeevatkm** [comment]
Yes, I am interested in it. Please keep me posted when you get a chance.

Also, your pointers for improving aah are very welcome.

**Comment by jeevatkm** [comment]
Documentation is done 😄 
https://github.com/go-aah/docs/blob/v0.11-edge/vfs.md
