### ISSUE TITLE
Routing mechanism needs step up

### ISSUE THREAD

**Issue by jeevatkm** [go-aah/aah#160]
This is all started with this issue #159 created by @vzool. Currently aah routing supports Radix Tree (aka BTree) algorithm.

Based on scenario he brought up also making aah much more flexible and robust. It needs step up in current routing mechanism.

aah users can look forward to improved routing mechanism with features on `v0.12.0` release. 

- [x] Implementation
- [x] Documentation

**Comment by jeevatkm** [comment]
@vzool I have started working on new router tree. once its completes I need your help on extensive testing. Thanks.

**Comment by jeevatkm** [comment]
@vzool I have almost done with new router tree implementation. Its ready for testing. 

Please follow the below steps to try new router and share your feedback.

* Go to `$GOPATH/src/aahframework.org/router.v0`
* Do `git pull --all && git checkout new-tree`

Now as usual you could proceed with your development actvities.

Pending/Progress things on my end -

* Already doing regression testing
* cleanup and streamline signatures and godoc (internal to library)
* I might add regex parameter feature if timeline permits otherwise I will move that enhancement to next release
* Any bug fix from your discovery/testing

FYI, I didn't not use bone router you have referred. It turns out that library did not use tree implementation. It just does loop and does route match.

**Comment by jeevatkm** [comment]
@vzool ping 😄

**Comment by vzool** [comment]
@jeevatkm pong 

![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f604.png)

**Comment by jeevatkm** [comment]
@vzool Did you get a chance to try it out?

**Comment by AugustHell** [comment]
Routing documentation along with some other topics is not available atm.
All of these links show a Not Found error: 
(same for previous versions)
https://docs.aahframework.org/v0.12/routing.html
https://docs.aahframework.org/v0.12/routes-config.html
https://docs.aahframework.org/v0.12/request-parameters-auto-bind.html
https://docs.aahframework.org/v0.12/request-and-response.html

**Comment by jeevatkm** [comment]
@AugustHell Thank you for reporting it. I will have a look.

**Comment by jeevatkm** [comment]
@AugustHell Now documentation is available, thanks again.

**Comment by AugustHell** [comment]
Thank you for strenuous efforts!
