### ISSUE TITLE
Incorrect mime-type on static content?

### ISSUE THREAD

**Issue by pharrisee** [go-aah/aah#182]
Hi,

I'm getting a browser side error:

````
Refused to execute script from 'http://localhost:8080/static/js/aah.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
````

This seems to be related to this header being set:

````
X-Content-Type-Options: nosniff
````

Since that header is set to nosniff the mime-type of the static files should be set explicitly.

This is when starting the aah app in dev mode with `aah r`.

**Comment by jeevatkm** [comment]
@pharrisee Okay, please let me know after your investigation then I will start analysis at my end. Is it a edge version?

**Comment by jeevatkm** [comment]
I have just did a small update on static file content type detection on single binary mode. You could refresh `aah s -r` to updates. 

FYI, aah single binary does optional decompression (sends already gzipped bytes as-is from VFS) while delivering static files 😄

**Comment by jeevatkm** [comment]
Any insights or test results would be helpful.

**Comment by jeevatkm** [comment]
I have verified at my end. With previous update on edge, its doing fine.
