### ISSUE TITLE
Planning v0.12.0

### ISSUE THREAD

**Issue by jeevatkm** [go-aah/aah#197]
Hello aah users -

As you know `v0.11.0` was released on Jul 06, 2018 with new features and enhancements. I hope you're liking it 😄 Thank you for your support.

----

Let's move on to next phase of development iteration focusing on v0.12.0

As you know aah development is community driven; based on community votes, suggestions and recommendations. I would priorities it. Looking forward to your inputs.

**My wish list -**

* Cache Manager - it would compliment to upcoming features in aah
* Scheduler - performing behaviour/action at defined intervals
* TestSuite for integration and functional test case #22 - long due item, let's flush it
* vgo - ogranize the aah modules and make more friendly towards `Versioned Go` (on every release, improvement will take place)

**If timeline permits -**

* Server-Sent Events (SSE) #125
* Make aah anatomy configurable #152 

_**Note:** I'm keeping tab on #161 Data Access Layer feature, also I have created a action items for the first release and few further items (it may not be in v0.12.0 release. However dev work will be started in parallel). Please have a look and share your thoughts._

---

Please have a look on [Open Issues](https://github.com/go-aah/aah/issues), [Roadmap](https://github.com/go-aah/aah/projects) or new item from your need; provide your wish list or vote on my wish list.

Then finally balanced wish list would be created. Thank you 😃

**Comment by jeevatkm** [comment]
@radutopala You're correct. That's the end goal. `vgo` name is used to target the efforts towards go modules work in aah.

**Comment by vzool** [comment]
@jeevatkm Hi, what about #160 on v0.12.0 ?

Thanks

**Comment by jeevatkm** [comment]
@vzool I did not forget that just I have not fully finished my homework on #160 as soon as I do I will include in the release. Thanks.

**Comment by jeevatkm** [comment]
I'm closing it, kick start of v0.12.0 dev iteration.
