### ISSUE TITLE
Console commands

### ISSUE THREAD

**Issue by radutopala** [go-aah/aah#198]
We should be able to run commands directly from the main binary if in prod env or through `aah` binary when in dev mode.

Please see Buffalo grifts at https://github.com/markbates/grift, https://github.com/gobuffalo/buffalo/tree/master/grifts.

---

- [x] Implement `console` module
- [x] Update aah CLI to use new console module
- [x] Adapt new console module for aah application binary (startup, version, etc)
- [x] Documentation

**Comment by jeevatkm** [comment]
@radutopala I like the idea. Could you provide further details on commands that would be a candidate to be run from `app/main` binary?

I could think of one action is database migrate from app library.

**Comment by radutopala** [comment]
@jeevatkm I'd see this as a generic gate for any kind of commands that a developer needs to create in his app, similar to what Symfony has done with the Console component Or Buffalo with Grifts.

So, basically, we should be allowed:
- to create N number of commands
- attach them to the main binary in prod or run them through `aah` in dev; in dev, commands should be parsed on-the-fly, let's say from the `root/command` folder; in prod, commands should be embedded in VFS

Examples can be numerous: db migration command, one-off commands, import commands, app specific setup commands etc

**Comment by radutopala** [comment]
@jeevatkm I've renamed the issue to be in line with the spec 😄

**Comment by vzool** [comment]
This even could behave like a background Tasks/Jobs run by cron :heart_eyes:

**Comment by jeevatkm** [comment]
@radutopala Here is the upcoming console commands documentation https://github.com/go-aah/docs/blob/v0.12-edge/console-commands.md

Could you have a look and let me know if you have questions?

**Comment by jeevatkm** [comment]
Done 😄

**Comment by radutopala** [comment]
@jeevatkm top notch, thx
