### ISSUE TITLE
Move auto-generated files to a cache folder

### ISSUE THREAD

**Issue by radutopala** [go-aah/aah#199]
Store the auto-generated `root/app/aah.go` and `root/app/aah_app_vfs.go` maybe in `root/app/cache/` or `root/cache`, just to be clear for the developer that these files shouldn't be editable and that they are auto-generated on each run or build.

**Comment by jeevatkm** [comment]
@radutopala Agreed. Its good to differentiate auto-generated files.

I believe directory `root/app/cache` would be appropriate, since directory `app` is meant for Go source files.

**Comment by jeevatkm** [comment]
Going with directory name as `generated` at `<app-base-directory>/app/generated`. Since v0.12.0 release bring new module `cache`. Just on safer side and not to introduced confusion.

It will be imported on main file. Example - 
```go
 _ "<app-import-path>/app/generated"
```

This directory gets cleaned on every run, compile and build.

**Comment by jeevatkm** [comment]
Done 😄
