### ISSUE TITLE
Session and Session Store

### ISSUE THREAD

**Issue by jeevatkm** [go-aah/aah#20]
* Session
* Session store - cookie and file
* Extensible store interface

**Comment by LeSou** [comment]
Session store - redis 

Is there no plan?

**Comment by jeevatkm** [comment]
Currently no @LeSou, sorry about that. However you can easily implement
 custom store and register in `aah`. Out-of-the box cookie and file store is supported.

Please refer this [session docs](https://docs.aahframework.org/session.html) for custom store.

**PS:** If you interested you can contribute your store implementation to https://github.com/aah-contrib, I can create a repo and can work with you to make it good for everyone.

**Comment by LeSou** [comment]
@jeevatkm  
I have achieved, can I participate in the development of the project? I am now using AAH in developing company projects

**Comment by jeevatkm** [comment]
@LeSou I'm glad to hear that you have started using aah framework. Your inputs and feedback is helpful.

You can contribute to aah project. Would you like to start with redis session store?

If yes then please let me know, I will create a repository under https://github.com/aah-cb and add you as user. Then we can work together to make it better.

**Comment by LeSou** [comment]
@jeevatkm  
It is nice to be able to contribute code to the project.
