### ISSUE TITLE
Getting started failed

### ISSUE THREAD

**Issue by rahmanme** [go-aah/aah#220]
#### What version of aah are you using (`aah --version`)?
Latest version

#### What operating system are you using (such as macOS, Linux and Windows)?
macOS

#### What did you do?
go get -u aahframework.org/aah.v0

#### What did you see instead?

...
aahframework.org/config.v0
# aahframework.org/config.v0
go/src/aahframework.org/config.v0/config.go:450:27: cannot use fs (type *"aahframework.org/vfs.v0".VFS) as type *"aahframe.work/vfs".VFS in argument to forge.VFSParseFile

**Comment by jeevatkm** [comment]
@rahmanme My bad, I'm working upcoming `v0.12.0` release. It will be out in day or two. 

Could you please try now? it should be alright. Also delete your existing path `go/src/aahframework.org/**`.

**Comment by jeevatkm** [comment]
@rahmanme I'm closing this one, please let me know the outcome.
