### ISSUE TITLE
aah build --single - does not work correctly when the code is inside a folder named "app"

### ISSUE THREAD

**Issue by vcraescu** [go-aah/aah#223]
I have the code set up in /app folder.
When I run `aah build --single` I get the following errors:

```
FATAL 
go: downloading aahframe.work/minify/html v0.1.0
go: downloading github.com/tdewolff/minify v0.0.0-20180913035026-a8ba821b5bd8
go: downloading github.com/tdewolff/parse v0.0.0-20180825090006-bcb5c6a1c04e
# xxxxxxxx/yyyyy/yyyyy/app/generated
app/generated/aah_app_vfs.go:6:2: imported and not used: "time"
app/generated/aah_app_vfs.go:9:2: imported and not used: "aahframe.work/vfs"
```

If I move the code into a different folder with a different name != /app, everything will work as expected. It seems that I cannot build the application inside a folder named "app".

**Comment by jeevatkm** [comment]
@vcraescu I have verified it. It seems if aah application base directory name is `app` then it fails with command `aah build --single` regardless of docker or not. Will update the issue subject and get to the root cause of it.

**Comment by jeevatkm** [comment]
@vcraescu I have fixed the aah CLI issue and made a CLI release `v0.13.1`. Please go ahead and install CLI, you should be good.

Thank you for reporting an issue.

**Comment by vcraescu** [comment]
Thanks!
