### ISSUE TITLE
Exclude subfolders on building single

### ISSUE THREAD

**Issue by radutopala** [go-aah/aah#245]
We need to be able to exclude subfolders on `build --single`.

Right now, if specified like this: `"./ui/public/*", "./ui/src/*", "./ui/test/*"`, they will still appear in `vfs find`.

**Comment by jeevatkm** [comment]
@radutopala I would like to understand directory structure for the project. Could you share some `tree` structure view?

_PS: If you would like to share via slack DM is also okay for confidentiality, I would like to learn some sample tree if possible_

**Comment by jeevatkm** [comment]
@radutopala Just to give you an insight into current implementation. 

aah CLI takes file `base` name from walk func and does the `filepath.Match` call for excludes. That's why your above definition didn't work.

**Comment by radutopala** [comment]
@jeevatkm well, I did a workaround for now and I wasn't required to have this deep subfolders exclusion after all. 
But it would be nice to have this feature in the framework itself, to be able to exclude subfolders like "<root>/ui/tests" OR full file paths "<root>/ui/config/conf.dist".

**Comment by jeevatkm** [comment]
@radutopala Thanks for your the input.

**Comment by jeevatkm** [comment]
It's done 😄
