### ISSUE TITLE
Override config not working for a single aah binary

### ISSUE THREAD

**Issue by adrianlop** [go-aah/aah#251]
#### What version of aah are you using (`aah --version`)?
cli v0.13.4
go  v1.12

#### Does this issue reproduce with the latest release?
yes

#### What operating system are you using (such as macOS, Linux and Windows)?
MacOS and Linux

#### What did you do?
`aah build -s`

#### What did you expect to see?
Override the config with `./aah-app run -c configfile.conf`

#### What did you see instead?
Values from the external file loaded with `-c` are not used if the application was built as a single binary

**Comment by jeevatkm** [comment]
@adrianlop I hope you're doing well.  I'm trying to wrap up the v0.13.0 release. Did a fixes and enhancements.  Then I will be moving on to aah revamp on v0.14.0

Can you please validate this issue against the branch `wrapping-v0.13.0` and let me know?
