### ISSUE TITLE
FATAL: go build: -i flag is deprecated / undefined: models

### ISSUE THREAD

**Issue by joelsdc** [go-aah/aah#273]
#### What version of aah are you using (`aah --version`)?

```
$ aah --version
aah v0.12.5
cli v0.13.6
go  v1.17
```

#### Does this issue reproduce with the latest release?

Yes

#### What operating system are you using (such as macOS, Linux and Windows)?

macOS

#### What did you do?

`$ aah r`

#### What did you expect to see?

My application build and run

#### What did you see instead?

```
$ aah r
---------------------------------------------------------------
             aah framework v0.12.5 (cli v0.13.6)
---------------------------------------------------------------
# Report improvements/bugs at https://aahframework.org/issues #

Loaded aah project file: /Users/joel/git/oncaller-api/aah.project
Hot-Reload enabled for environment profile: dev
Compile starts for 'oncaller-api' [my.domain.com/ops/oncaller-api]
FATAL
go build: -i flag is deprecated
# my.domain.com/ops/oncaller-api/app/generated
app/generated/add_controllers.go:39:43: undefined: models
app/generated/add_controllers.go:47:43: undefined: models

exit status 2
```

**Comment by vulcangz** [comment]
My blind guess is that `models` can't be exported and the first letter has to be capitalized.

**Comment by joelsdc** [comment]
With the latest updates with aah CLI and go version (in my case, go v1.18) this no longer happens.

Thanks!
