### ISSUE TITLE
Hot-Reload for Development

### ISSUE THREAD

**Issue by jeevatkm** [go-aah/aah#4]
Goal is to provide `hot-reload` capabilities for development, so that it helps developer to have fun development.

#### What is Hot-Reload?
To reflect changes made in Static Files (js, css), View template file and Go Source Code without manual intervention (i.e. manually stopping server and starting the aah server). Instead aah CLI will do monitoring/watch on aah project and does automatic stop, compile and start the aah server.

#### Design and Implementation
Approach and solution will be done in aah cli tool. It is not applicable for `prod` environment profile. It highly recommended to build and deploy the archive for production use.

#### Static Files
aah framework delivers static file using standard library func `http.ServeContent`, which is by default adds the `Last-Modified` response header and by default modern web browser does cache the static files locally.

Solution is to prevent cache and deliver file always- (only for `dev` environment profile)
* Set these HTTP headers
    - `Cache-Control: no-cache, no-store, max-age=0, must-revalidate`
    - `Expires: 0`

#### Go Source directory, view directory, config directory
Typically every go program gets compiled before the execution. The view template files compiled and stored in memory on server start.  

Solution is to reflect code changes - (only for `dev` environment profile)
* Monitor files and directories 
* If change event occur then stop the server, recompile and then start the server
* There are limitation to this, will document it later on.
      * Standard Library Path is not applicable i.e. `GOROOT`

Will try to bring this feature as early as possible.

* [x] Static Files
* [x] View Template Files
* [x] Go Source Code
* [x] Config Files

**Comment by elevenbag** [comment]
how long will it take?

**Comment by jeevatkm** [comment]
@elevenbag Currently I'm working to wrap up `v0.6` release. Then I will be targeting this feature for `v0.7`

Thank you for your interest.

**Comment by elevenbag** [comment]
Can I participate in development? I am currently adding caches

**Comment by jeevatkm** [comment]
If would like to contribute to aah framework. Please let me know your idea before you work on, so that we can choose the feature or enhancement aligning with roadmap.

Based on that I will suggest, whether new repo needed [here](http://github.com/aah-cb) for you to do the implementation or Submitting PR.

**Comment by jeevatkm** [comment]
Also please go thru the codebase to get understanding of how it is organized, structure, style, etc.

I use `gometalinter` with atom editor for code quality.

**Comment by jeevatkm** [comment]
Cleaning up few comments that doesn't belongs to this thread. Anyway conversation took place another thread.

**Comment by elevenbag** [comment]
I look forward to your good news.

**Comment by jeevatkm** [comment]
I have evaluated [fsnotify](https://github.com/fsnotify/fsnotify) and [watcher](https://github.com/radovskyb/watcher) library for monitoring file and directory changes. 

I believe watcher library would be better fit for aah framework, I have created issue at watcher library radovskyb/watcher#20 to get few clarifications before I start integrating into aah framework.

**Comment by adelowo** [comment]
I have used `fsnotify` before and i can say it is a good fit too..

**Comment by jeevatkm** [comment]
@adelowo Yes I agree with you, I'm it using too. `fsnotify` was my first choice then I come across `watcher` library without using filesystem events. 

I will wait for response then we can take final choice.

**Comment by jeevatkm** [comment]
It's done, hooray!
