### ISSUE TITLE
create multiple controllers?

### ISSUE THREAD

**Issue by LeSou** [go-aah/aah#46]
Hi, Does it support creating multiple controllers?

frontend
  └ controllers      
  └ models                 
backend
  └ controllers      
  └ models

**Comment by jeevatkm** [comment]
Yes, `aah` supports multiple controllers. 

However it's not like your package definition. Please have a look [aah anatomy](https://docs.aahframework.org/anatomy-aah-application.html). All the go source code reside in `app` directory and all the controllers reside in `app/controllers`. Keep the models outside controllers package like `app/models`.

You can define following:
```
app
  └ controllers
      └ frontend
          └ v1
              └ ...
          └ v2
              └ ...
      └ backend
          └ v1
              └ ...
          └ v2
              └ ...
      └ ...
```

When you map the controller in the [`routes.conf`](https://docs.aahframework.org/routes-config.html), map it along with `package`.

For example:
```
route_name {
    # other routes config
    # ...

    # map it along with package
    controller = "frontend.v1.YourController"

    # ...
}
```

Please let me know, if you any queries. Thank you for using aah framework.

**Comment by LeSou** [comment]
thank you

**Comment by jeevatkm** [comment]
Please let me know, if you face any issues using `aah framework`. I'm glad to assist you.
