### ISSUE TITLE
Tweak route config file based on the type of project to be created

### ISSUE THREAD

**Issue by adelowo** [go-aah/aah#47]
If i create an api project with `aah new`, `appdir/config/routes.conf` contains some options commented out with "Perfect for restful api"..

I am suggesting those be uncommented by default..  For example, a `405` status reply is kind of standard for every api

**Comment by jeevatkm** [comment]
Actually those values are `true` by default, [reference to docs](https://docs.aahframework.org/routes-config.html#redirect-trailing-slash). 

You will get that behavior, even if it's commented. It make sense to remove comment when `aah new` for an api application.  I will update the templates. Thanks.

**Comment by adelowo** [comment]
Oh, I haven't gone through the docs properly though.

**Comment by jeevatkm** [comment]
No problem. I have updated the templates. Next release will have uncommented lines for `api`. Thanks for your inputs.

**Comment by jeevatkm** [comment]
Done
