### ISSUE TITLE
wildcard subdomain support

### ISSUE THREAD

**Issue by ghost** [go-aah/aah#49]
I've set up a rudimentary alternative using **Server Extension** but might be better in the router itself.

**Comment by jeevatkm** [comment]
I will add the support for wildcard subdomain. Thanks.

**Comment by jeevatkm** [comment]
Now in the wildcard subdomain supported in the `host` attribute of `routes.conf`.

```
host = "*.sample.com"
```

And in the controller, you call `Subdomain` method to get the subdomain name.

For e.g.:

```go
// request comes to jeevatkm.sample.com
Subdomain() 

// Returns
// jeevatkm
```

If it's not a subdomain then method returns empty string.
