### ISSUE TITLE
centralized error handler

### ISSUE THREAD

**Issue by ghost** [go-aah/aah#57]
Something like this: [https://echo.labstack.com/guide/error-handling](https://echo.labstack.com/guide/error-handling)
[https://laravel-news.com/laravel-5-5-error-views](https://laravel-news.com/laravel-5-5-error-views)

- [x] Implementation
- [x] Documentation

**Comment by jeevatkm** [comment]
Sounds good, I will add it to the roadmap. Thanks.

**Comment by julienkosinski** [comment]
Also, it could support error reporting for Sentry for example. https://github.com/getsentry/raven-go

**Comment by jeevatkm** [comment]
Centralized error handler implementation is done, came out very good. Available on edge version.

Documentation is in progress.
