### ISSUE TITLE
template authenticated bug fix

### ISSUE THREAD

**Issue by elevenbag** [go-aah/aah#59]
```
func (ctx *LoginController) Login() {
      ctx.Session().IsAuthenticated = true
}

func (ctx *LoginController) Logout() {
   ctx.Session().IsAuthenticated = false
}

{{ if isauthenticated . }}
  <a href="/logout">Logout</a>
{{ end }}
```

`IsAuthenticated = false;   `
show logout option ?

**Comment by elevenbag** [comment]
This is the implementation of the exit
```
func (ctx *LoginController) Logout() {
   ctx.Session().IsAuthenticated = false
   ctx.Session().Clear()
   ctx.Reply().Redirect("/")
}
```

Delete` ctx.Reply().Redirect("/") `normal

**Comment by jeevatkm** [comment]
Just clarifying my understanding, do you mean to say session is not cleared when redirect happens?

**Comment by jeevatkm** [comment]
Found the issue, fix will be in `v0.6`.

@elevenbag Thanks for reporting a bug.

**Comment by elevenbag** [comment]
@jeevatkm 
There is still a mistake。

`fmt.Println(ctx.Session().IsAuthenticated)  //true`

Not show
```
{{ if isauthenticated . }}
  <a href="/logout">Logout</a>
{{ end }}
```

**Comment by elevenbag** [comment]
@jeevatkm 
```
ctx.Session().Set("uid", 2)

html
{{ session . "uid" }}
```

Cannot output normally

**Comment by jeevatkm** [comment]
This fix is not yet released. Did you manually applied a fix into your local codebase?

Could you please share the sample application demonstrating these two issues Session value display in html and `isauthenticated`? It would help me.

I would like to fix this as soon as possible before the v0.6 release.

**Comment by elevenbag** [comment]
@jeevatkm 

App.go
```
func (a *App) Index() {
	data := aah.Data{}
	data["uname"] = a.Session().GetString("uname")
	a.Reply().Ok().HTML(data)
}

func (a *App) Login() {

	sess := a.Session()
	sess.IsAuthenticated = true
	sess.Set("uid", 2)
	sess.Set("uname", "demo")

	a.Reply().Ok().Redirect("/")
}

```
aah.conf

```
 login {
          path = "/login"
          controller = "App"
          action = "Login"
      }
```
index.html
```
{{ define "title" -}}
<title>{{ i18n . "label.pages.app.index.title" }}</title>
{{- end }}

{{ define "body" -}}



{{ if isauthenticated . }}
<a href="/logout">Logout</a>
{{ end }}
<br/>
{{.uname}} => {{ session . "uid" }}


{{- end }}

```

**Comment by elevenbag** [comment]
@jeevatkm 
$ git branch -vv
* v0-unstable 6deec18 [origin/v0-unstable] #59 session clear fix while redirect happens

**Comment by jeevatkm** [comment]
@elevenbag Thank you for the details. Here 1 AM, I'm fleeing sleepy going to bed.

Tomorrow I will get back to you.

**Comment by elevenbag** [comment]
OK, thank you

**Comment by jeevatkm** [comment]
@elevenbag Bingo found the problem. Session clear fix on redirect introduced this problem. Actually view was not getting the session object.

Now you get can test it and let me know. Thanks.

**Comment by jeevatkm** [comment]
@elevenbag did you get a chance to verify it?

**Comment by elevenbag** [comment]
@jeevatkm  Solve, thank you

**Comment by jeevatkm** [comment]
@elevenbag You're welcome.
