### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by blagodus** [go-aah/aah#65]
I got this error when i try to run `go get -u aahframework.org/tools.v0/aah`..

```
error: RPC failed; HTTP 301 curl 22 The requested URL returned error: 301
fatal: The remote end hung up unexpectedly
package aahframework.org/tools.v0/aah: exit status 128
```

**Comment by jeevatkm** [comment]
It seems like connectivity issue with `git`.

Could you please try this and share the output (test purpose, delete it after test)?
```
git clone -v https://aahframework.org/tools.v0
```

If above git clone success then your installation would be success.
```
go get -u aahframework.org/tools.v0/aah
```

**Comment by DimShadoWWW** [comment]
I have the same error:

$ git clone -v https://aahframework.org/tools.v0
Cloning into 'tools.v0'...
POST git-upload-pack (615 bytes)
error: RPC failed; HTTP 301 curl 22 The requested URL returned error: 301
fatal: The remote end hung up unexpectedly

**Comment by jeevatkm** [comment]
@DimShadoWWW Thank you for the details:

Please set this git config:
```
git config --global http.https://aahframework.org.followRedirects true
```

Let me know the outcome.

**Comment by blagodus** [comment]
After setting:
`git config --global http.https://aahframework.org.followRedirects true`
installation works..

**Comment by jeevatkm** [comment]
@blagodus Thank you for the confirmation.

If you ran into any issues or if you have any questions, please let know.
