### ISSUE TITLE
Server Access Log

### ISSUE THREAD

**Issue by jeevatkm** [go-aah/aah#69]
To manage server effectively it is necessary to know details about the request, response, processing time, client IP address, etc. aah framework provides the flexible and configurable access log capabilities.

aah server logs the details based on log flags. Flag format usage is `%flagname`

**The available flags as follows:**

* `clientip` - Client IP address aka Remote IP address
* `reqtime` - Time of request is recevied by server. Local time in default format RFC3339 or you can provide one
* `requrl` - Request URL not including query string
* `reqmethod` - Request HTTP method
* `reqid` - It logs request id otherwise it logs `-`. Refer `request.id.header` config in the `aah.conf`
* `reqhdr:<header_name>` - To log request header, if not available `-` is logged
* `querystr` - To log request query string if available otherwise `-` is logged
* `resstatus` - Response Status
* `ressize` - Bytes sent, excluding response HTTP headers, otherwise `-` if no bytes were sent
* `reshdr:<header_name>` - To log response header, if not available `-` is logged
* `restime` - Request processing time (in milliseconds), time elapsed between the request recevied by server and the last bytes were written on the wire by server

Access log processing should not affect the app perfomance.

**Access Log Configuration:**

```
request {
   access_log {
      # Default is false
      enable = false

      # Absolute path of log file
      # Default location is application logs directory
      file = "<appname>-access.log"

      # This is default access log pattern
      pattern = "%clientip %reqid %reqtime %restime %resstatus %ressize %reqmethod %requrl"
   }
}
```

* [x] Implementation - PR by @adelowo #72 
* [x] Documentation
* [x] App template update

**Comment by jeevatkm** [comment]
@adelowo Please join [gitter](https://gitter.im) share your User Id then I will invite you into the [dev](https://gitter.im/aahframework/dev-team) channel. This is private channel for dev-team.

**Comment by adelowo** [comment]
Id -> 58266a50d73408ce4f3546ba
username -> adelowo

**Comment by jeevatkm** [comment]
Just added you into the dev channel.

**Comment by adelowo** [comment]
This (https://github.com/go-aah/tools/blob/v0-unstable/aah/app-template/config/aah.conf.atmpl#L109-L123) would also have to be updated... At least it should contain `request.access_log.enable`.

**Comment by jeevatkm** [comment]
You're correct, after merging your PR, Then `app-template` will be update with request access log configuration with default values. I will take care that.
