### ISSUE TITLE
Make i18n URL query parameter name configurable and add support for path variable.

### ISSUE THREAD

**Issue by jeevatkm** [go-aah/aah#71]
Bringing more then one options of internationalization and localization override. Default is based on HTTP header `Accept-Language`. However real world usage requires overrides too.

aah framework provides override via -
* [x] **Path Variable:** i.e. `/:lang/home.html`, `/:lang/aboutus.html`, etc.
      * For e.g.: `/en/home.html`, `/en/aboutus.html`, `/zh-CN/home.html`, `/zh-CN/aboutus.html` etc.
* [x] **Query Parameter:** i.e `?lang=en`, `?lang=zh-CN`, etc. This is already supported, just we have to make param name configurable.

**Note:** Query parameter takes precedence of all.

**aah.conf:**
```
i18n {
    param_name {
        # Default value is `lang`
        path = "locale"

        # Default value is `lang`
        query = "locale"
    }
}
```
* [x] app template 
* [x] Documentation

**Comment by adelowo** [comment]
I don't understand the second item on the checklist.. Can you explain that better ?

**Comment by jeevatkm** [comment]
I have update the design description. Path variable value is accessible via `ctx.Req.PathValue("lang")`.

**Comment by adelowo** [comment]
Ok, I see you updated the config structure (from `i18n.url_param_name`).. That renders #73 void ?

**Comment by jeevatkm** [comment]
You no need to close #73, continue to update and push changes to the same PR.

**Comment by adelowo** [comment]
@jeevatkm can you work on the "path variable".. I wouldn't be chanced to do much for some days. Maybe you pick up #73 from it's current state

**Comment by jeevatkm** [comment]
No issues, I will take care, Thanks.
