### ISSUE TITLE
aah --version and aah -v bug on Windows

### ISSUE THREAD

**Issue by julienkosinski** [go-aah/aah#80]
Hello,

First of all, thank you very much for the great framework it really is wonderful because it's a crystal clear framework with many useful functionalities and with great choices! :D

I'm on:
`go version go1.8.3 windows/amd64`

So, I have this bug following this steps:
`git config --global http.https://aahframework.org.followRedirects true`
`go get -u aahframework.org/tools.v0/aah`

```
aah --version
flag provided but not defined: -version
Usage of F:\{my_path}\aah.exe:
```
```
aah -v
flag provided but not defined: -v
Usage of F:\{my_path}\aah.exe:
```

Everything else works well.

Thank you very much :).

**Comment by jeevatkm** [comment]
@julienkosinski Thank you so much for your appreciation. I'm very glad have your appreciation on social channel to too :) 

This is surprise to me.  

`aah --version` and `aah -v` (posix flags)  upcoming in `v0.7` release. I have improved a lot on aah cli.

In the `v0.6` release you have to `aah version`.  Can you please try this?

I would like to know, how come you know the new flags without using dev code base?

**Comment by julienkosinski** [comment]
You're right, I'm on v0.6 and so it's the command aah version.
It may have a problem with the import because it installed 0.6 instead of 0.7?

**Comment by jeevatkm** [comment]
`v0.7` is not yet released, it's upcoming one. 

I'm working on it (major highlights are security authentication and authorization, server access log, few enhancements... ).

**Comment by julienkosinski** [comment]
Ok, so that's my fault, in fact the doc is updated with the functionalities of 0.7 as you are finishing them!

I'll let you finish it :).

Thank you very much!

**Comment by jeevatkm** [comment]
Thank you @julienkosinski.

If you any questions or issues, please reach out via github issues or gitter.

**Comment by julienkosinski** [comment]
@jeevatkm Thank you very much for your reactivity! I'll closely follow aah! :D
