### ISSUE TITLE
Max Request Body Size

### ISSUE THREAD

**Issue by jeevatkm** [go-aah/aah#83]
It is recommend to limit request body size with `sane` size value. It prevents the application from 

> Avoiding DDoS attacks caused by large HTTP request bodies by enforcing a hard limit in your server

Goal is to provide Max Request Body Size for all routes (aka global limit) and individual routes too.

**Comment by adelowo** [comment]
Hi @jeevatkm, as per the global limit, I see there is already a config value `server.max_header_bytes` which defaults to `http.DefaultMaxHeaderBytes` (`1MB`) already. What option are you looking at with the individual routes ? `routes.index.max_header_bytes` ? That is should `max_header_bytes` be located in each route config block ? I should be able to work on this next week (if you don't already have it done :smile: )

**Comment by jeevatkm** [comment]
@adelowo This is for `Body` size limit not a HTTP Headers size limit.

**Comment by jeevatkm** [comment]
@adelowo Currently I'm working on content negotiation #75

**Comment by adelowo** [comment]
Lol, I am sorry I mixed it up. Wasn't thinking straight.

**Comment by jeevatkm** [comment]
Implemented and merged :)
