### ISSUE TITLE
REST API with Generic Auth tutorial?

### ISSUE THREAD

**Issue by kieusonlam** [go-aah/aah#85]
Hi,

I cannot create new tag on stackoverflow. And I'm not pretty sure if I can ask question here.

I really like this project structure and everything you guys have integrated like Authentication & Authorization. 

I'm new to Go. I trying to make a blog with rest api server. What should I do to get the token when using Generic Auth. Make a POST Request to `/login` route and what should I write in the controller?
```
{
  "username": "demo",
  "password": "demo"
}
```
----
By the way if I want to use gorm for my project. How should I structure my aah project. I don't want to mess everything up :)

Thanks

**Comment by joelsdc** [comment]
Hi, 

First thing I have to say is I'm new to GO too. For `Q1` I assume @jeevatkm will have to reply. For `Q2`, I can tell you what I'm doing (different library though).

I'm using [Go Relational Persistence](https://github.com/go-gorp/gorp) with aah project.

Inside my project structure, I created a new package called `db`, inside it I created a `datasource.go`:

```
├── README.md
├── aah.project
├── app
│   ├── aah.go
│   ├── controllers
│   │   ├── app.go
│   │   ├── ....go
│   │   └── ....go
│   ├── db
│   │   └── datasource.go
│   ├── models
│   │   ├── ....go
│   │   ├── ....go
│   │   └── ....go
│   └── services
│       ├── ....go
│       └── ....go
├── config
│   ├── aah.conf
│   ├── env
│   │   ├── dev.conf
│   │   └── prod.conf
│   ├── routes.conf
│   └── security.conf
├── i18n
    └── messages.en
```

That `db` package  (datasource.go) has the following implementations:

```go

var (
	// SQL DB variable declarations (1 per datasource: check config/env/*)
	sampledb *sql.DB
	
	// Db is database mapping
	Db *gorp.DbMap

	ErrDBConnectionUnavailable = errors.New("DB connection unavailable")
)


// Transaction is to handle Db transactions
type Transaction struct {
        *gorp.Transaction
}


// DatabaseInit initializes the Database.
func DatabaseInit(e *aah.Event) {
	cfg := aah.AppConfig()
	var err error

	// Start db config: sampledb (connection, ping, table mapping)
	sampledb, err = sql.Open(
		cfg.StringDefault("datasource.sampledb.driver", ""),
		cfg.StringDefault("datasource.sampledb.url", ""))
	if err != nil {
		log.Error(err)
		return
	}

	if err = sampledb.Ping(); err != nil {
		log.Error(err)
		return
	}
	log.Info("DB sampledb connection and Ping is successful")

	sampledb.SetMaxIdleConns(cfg.IntDefault("datasource.sampledb.max_idle_conns", 3))
	sampledb.SetMaxOpenConns(cfg.IntDefault("datasource.sampledb.max_open_conns", 50))

	Db = &gorp.DbMap{
		Db:      sampledb,
		Dialect: gorp.MySQLDialect{Engine: "InnoDB", Encoding: "UTF8"},
	}

	// Table mapping
        //...

	// End db config: sampledb
}


// DatabaseClose closes the Database.
func DatabaseClose(e *aah.Event) {
	if sampledb != nil {
		_ = sampledb.Close()
	}
}


// GetTxn returns the DB transaction.
func GetTxn() *Transaction {
        t, err := Db.Begin()
        if err != nil {
                log.Error(err)
                return nil
        }
        return &Transaction{Transaction: t}
}


// CommitOrRollback commits or rollback if error.
func (t *Transaction) CommitOrRollback() {
        if t.Transaction != nil {
                if err := t.Transaction.Commit(); err != nil && err != sql.ErrTxDone {
                        if err = t.Transaction.Rollback(); err != nil && err != sql.ErrTxDone {
                                log.Error(err)
                        }
                }
                t.Transaction = nil
        }
}

// Using aah server extension points (on start, on shutdown, etc...) 
func init() {
	aah.OnStart(DatabaseInit)
	aah.OnShutdown(DatabaseClose)
}
```


And this is how I call it in the services package:


```go
func (s *SampleService) Info(param1 int) *models.SampleInfo {
        txn := db.GetTxn()
        defer txn.CommitOrRollback()

        var sampleInfo models.SampleInfo
        err := txn.SelectOne(&sampleInfo, "SELECT blablabla FROM table WHERE condition = ?", param1)
        if err != nil {
                log.Error(err)
                return nil
        }

        return &sampleInfo
}
```

In my env config profiles (dev.conf, prod.conf, etc...) I have the appropriate config values:

```
...
datasource {
    sampledb {
      driver = "mysql"
      url = $DB_CONNECTION_STRING
      max_idle_conns = 3
      max_open_conns = 50
    }
  }
...
```

Hope this helps.

Joel.

**Comment by jeevatkm** [comment]
@kieusonlam First of all I'm sorry. I didn't get a time to create REST API with Generic auth tutorial before the v0.7 release. I will create it today and let you know.

I'm glad to hear, you liked the aah project structure.

In the mean time, get familiar with [Generic auth configuration](https://docs.aahframework.org/authentication.html#generic-auth). Security Manager gets the auth token and passes as a argument to method `GetAuthenticationInfo`. You will get more understanding from the tutorial.

@joelsdc Than you for your inputs, it helps the aah community.

**Comment by kieusonlam** [comment]
@jeevatkm Thanks! Looking forward to seeing it.

@joelsdc Thanks. I have another question :) Should we always open Database Connection when app is running? I found this turorial. He open and close Database Connection every action. Is that good or is that bad?

**Comment by adelowo** [comment]
@kieusonlam The db connection should be opened once and only closed when the app is shutting down - since it is a long running process, it differs from say `PHP` where a new `HTTP` request starts the entire process.

**Comment by joelsdc** [comment]
> I found this turorial. 

@kieusonlam I think you didn't link to the URL. Can you post the tutorial? I'd love to have a look.

**Comment by kieusonlam** [comment]
@joelsdc My bad. Here is it: https://medium.com/@etiennerouzeaud/how-to-create-a-basic-restful-api-in-go-c8e032ba3181

**Comment by jeevatkm** [comment]
@kieusonlam I had a look on the article. The way `InitDb` is implemented and usage is not recommended or correct way.

Go `database/sql` package effectively manages the Db connections via pooling. Right way to go is:
* Initialize the DB once at application startup
* Use the already initialized DB instance to get the transaction as needed using [DB.Begin](https://golang.org/pkg/database/sql/#DB.Begin) or [DB.BeginTx](https://golang.org/pkg/database/sql/#DB.BeginTx) 
* Then Commit/Rollback and Close the connections at the end of the operation (when connection is closed it goes to pool)

These properties plays vital role in the connection pooling
* [SetMaxIdleConns](https://golang.org/pkg/database/sql/#DB.SetMaxIdleConns)
* [SetMaxOpenConns](https://golang.org/pkg/database/sql/#DB.SetMaxOpenConns)

I hope it helps.

**Comment by jeevatkm** [comment]
@kieusonlam I have added the tutorial aah application of REST API generic auth here https://github.com/go-aah/tutorials/tree/master/rest-api-generic-auth

Please go through and let me know if you have any questions or doubts.

I need to create documentation page for this tutorial application, once done I will let you know.

**Comment by kieusonlam** [comment]
@jeevatkm Thank you for helping me out. I tried it. I make a `GET` request to `http://localhost:8080/v1/reportee/user1@example.com`
![image](https://user-images.githubusercontent.com/13093313/28995252-b4d15846-7a0e-11e7-8079-8386df67069f.png)
I got this. Am I doing it wrong?

By the way I want a example look like this
https://echo.labstack.com/cookbook/jwt
Could you help me with that :) Get the token after make a POST request to login route. 

A have a little confuse about how to work with controller after make a POST request to generate the token.

**Comment by jeevatkm** [comment]
@kieusonlam You're missing `Bearer ` prefix before the token on Authorization header.

Typically API services takes token and validates with identity management system. Generic Auth tutorial demonstrates that one.

Also I will create JWT tutorial for you with token generation (POST request) and validating income request. 

I understood your question, Once I create a documentation explaining the tutorial. Then you will see that's very easy to do.

_Tip: Take a moment to compare Generic Auth tutorial and JWT Auth tutorial, you will see aah is very flexible and powerful._

**Comment by jeevatkm** [comment]
@kieusonlam REST API using JWT auth Tutorial with documentation is ready.

https://docs.aahframework.org/tutorial/rest-api-jwt-auth.html

**Comment by jeevatkm** [comment]
Closing it, @kieusonlam anytime let me know if you any queries.

**Comment by kieusonlam** [comment]
@jeevatkm Thank you so much. That exactly what I am looking for.

I also try it with Bearer prefix. 
![image](https://user-images.githubusercontent.com/13093313/29002864-5921b1bc-7ad6-11e7-8e76-47d99023b5f6.png)
Here is my console log
```
2017-08-06 18:36:44.358 INFO  AuthenticationToken:: Scheme: generic, Identity: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
.eyJleHAiOjE1MDIyNzg0ODQsInVzZXJuYW1lIjoiYWRtaW5AZXhhbXBsZS5jb20ifQ.5LuzjO-26rXJTqrsCj8DzEO-2v1Ryftpmsb_E4fdXuY, Credentia
l: *******
2017-08-06 18:36:44.358 WARN  generic: authenticator is not properly configured in security.conf
2017-08-06 18:36:44.358 INFO  Authentication is failed
```

**Comment by jeevatkm** [comment]
@kieusonlam Tutorial should work properly. Which one it is generic tutorial and JWT auth?

Also issue is as log states, check the `security.conf` of config attribute `authenticator`.
```
2017-08-06 18:36:44.358 WARN  generic: authenticator is not properly configured in security.conf
```

**Comment by kieusonlam** [comment]
@jeevatkm All there of auth tutorial, I got the same error. I didn't change anything from the source code. 

My PC: Windows 10
go version go1.8.3 windows/amd64

**Comment by jeevatkm** [comment]
This is surprise. Okay Windows OS, Let me check with my windows VM and get back. Thank you.

**Comment by jeevatkm** [comment]
@kieusonlam I have just verified in my Windows 10 VM. all the tutorials are running fine. Could you please join gitter chat? then we can analyze it why you're getting an issue.

**Comment by jeevatkm** [comment]
@kieusonlam If you want we can have screen share session too.

**Comment by kieusonlam** [comment]
@jeevatkm I tried on another computer, it's work. Sorry for bordering you so much. I may try to figure out what wrong with my computer. If I stuck on something, I will join gitter. Thanks again.

**Comment by jeevatkm** [comment]
@kieusonlam no problem. Glad to hear, you got it working.
