### ISSUE TITLE
How to relate access_log with application log?

### ISSUE THREAD

**Issue by joelsdc** [go-aah/aah#86]
Hi, 

I like the way you can configure the format of the access_log file. If I include the request-id in the access_log, how can I correlate a request with events in the application log?

For example:

Application log:
```
2017-08-04 10:11:14.560 INFO  AuthenticationToken:: Scheme: basic, Identity: testuser, Credential: *******
2017-08-04 10:11:14.560 INFO  AuthenticationInfo:: Principals[Realm: , Principal: testuser, IsPrimary: true], Credential: *******, IsLocked: false, IsExpired: false
2017-08-04 10:11:14.576 INFO  Authentication successful
2017-08-04 10:11:14.589 ERROR Could not find number: 00000000
```

Access_log:
```
A.B.C.D - 2017-08-04T10:11:26-05:00 GET /v1/test/00000000 HTTP/1.1 200 305 35.4264 -
```

If I add the `reqid` value to the access_log I get the following:

```
"5984a6098a5da56c2b3b1856" - A.B.C.D - 2017-08-04T10:11:26-05:00 GET /v1/test/00000000 HTTP/1.1 200 305 35.4264 -
```

Is there a way to add the `reqid` also to the application log?

Also, I would't have the `"` (quotes) printed when referring to the `reqid` variable, I don't know if there is a specific reason for that.

Thanks, 
Joel.

**Comment by jeevatkm** [comment]
@joelsdc I understand your use case. Let me think of best approach to solve this use case. I will get back to you.

**Comment by jeevatkm** [comment]
Best approach is to solve this use case is bringing context based logging support in aah.

**Comment by jeevatkm** [comment]
@joelsdc #111 would bring this feature in `v0.9`. I'm closing this one.
