### ISSUE TITLE
Logging request/response body. 

### ISSUE THREAD

**Issue by joelsdc** [go-aah/aah#87]
Hi, 

Is there a way to dump to a file (possibly, different from access/application log) the request and/or response body? 

If there is, I would have the same doubt as #86.

Thanks, 
Joel.

**Comment by jeevatkm** [comment]
@joelsdc Currently this feature does not exists in aah. I will add this into Roadmap. Thank you.

**Comment by jeevatkm** [comment]
Dump of Request and Response details (headers, body) coming in `v0.9` :)

**Comment by joelsdc** [comment]
Thanks!

**Comment by jeevatkm** [comment]
Merged
