### ISSUE TITLE
User-friendly password bcrypt hash generator command in aah

### ISSUE THREAD

**Issue by joelsdc** [go-aah/aah#89]
Hi, 

This is a feature request. I'm trying the BASIC-AUTH.. 

In the documentation I see:
```
      # Password encoder is used to encode the given credential and then compares
      # it with application provide credential.
      # Currently supported hashing is `bcrypt`, additional hash types (upcoming).
      password_encoder {
        # Default value is `bcrypt`.
        #type = "bcrypt"
      }
```

Background...

The most common tool to generate password hashes is `mkpasswd`, and, bcrypt is not supported:

```
root@test:/opt/aah/test-api# mkpasswd -m help
Available methods:
des    standard 56 bit DES-based crypt(3)
md5    MD5
sha-256    SHA-256
sha-512    SHA-512
root@test:/opt/aah/test-api#
```

This means that to generate a brypt password, you have to install a different tool, use an online generator or run a script in some language (python, perl, ruby, etc..) that has a bcrypt compatible crypto library...

Can you provide a way to generate such bcrypt hash? 

As a suggestion:

`aah mkpasswd <plain_text_password>`
```
root@test:~# aah mkpasswd welcome123
$2a$06$GJqVf065cJeAz4PBnhOXyuM9ufttc6SbmXPwkJFad51n5l/JRaP1a
root@test:~#
```

Or interactive if left blank:

`aah mkpasswd`
```
root@test:~# aah mkpasswd
Password:
$2a$06$GJqVf065cJeAz4PBnhOXyuM9ufttc6SbmXPwkJFad51n5l/JRaP1a
root@test:~#
```
(I found [this library](https://github.com/howeyc/gopass) that can possibly help you with the interactive implementation)

Or similar...

Maybe even being able to specify the hash algorithm from one of the supported ones, using as default the one set in security.conf?

This feature request isn't trying to be lazy, it's just that sometimes installing extra stuff on servers is restricted and I really don't want to get into the "use an online password hash generator" discussion ;)

Let me know what you think.

Thanks, 
Joel.

**Comment by adelowo** [comment]
I don't seem to find a valid usecase for `aah mkpasswd` :confused:

**Comment by joelsdc** [comment]
@adelowo I'll explain my usecase, maybe you can give me a better approach or maybe I missed something really trivial that solves this...

Say you have enabled BASIC-AUTH in security.conf.

```
security {
  auth_schemes {
    basic_auth {
      scheme = "basic"
      realm_name = "Protected"
      file_realm = /opt/aah/test-api/config/api_basic_realm.conf
      password_encoder {
        type = "bcrypt"
      }
    }
  }
```

Now, in the credentials file I have:

```
root@test:~# cat /opt/aah/test-api/config/api_basic_realm.conf
testuser {
  password = "$2a$06$GJqVf065cJeAz4PBnhOXyuM9ufttc6SbmXPwkJFad51n5l/JRaP1a"
  roles = ["admin", "supervisor"]
}
root@test:~#
```

My request of `aah mkpasswd <...>` is exactly for this case. How would you generate the password bcrypt hash?

**Comment by jeevatkm** [comment]
@joelsdc I think it might be helpful for `bcrypt`, `scrypt` and `pbkdf2` algorithms. Since these algorithm requires to write some code to generate a hash. No ready to use tool exists. So `aah cli` might become handy.

However for `md5`, `sha-256` and `sha-512` hashing you can use the `mkpasswd` tool.

**Comment by adelowo** [comment]
@joelsdc ,  I would use a REPL for this (e.g gore). BTW I read your original comment about using another language for generation of bcrypt hashes. Go has an awesome crypto lib though.

```go
:import "golang.org/x/crypto/bcrypt"

hashedInBytes, _ := bcrypt.GenerateFromPassword([]byte(p), bcrypt.DefaultCost)
string(hashedInBytes)
```
> This is for gore

**Comment by adelowo** [comment]
@jeevatkm Another thing I am thinking of is this. Would it sound better if this gets added to the `essentials` package. That way, the user can quickly use a REPL for this or generate users' password to put into some storage - `ess.GeneratePassword(algoType string, plainPassword string) (string, error)`.

I still don't feel it is worth adding this to the standard tool cli. If this gets added, `aah mkapitoken` would be requested too in the future by users who would like to have random/tests api token (if using building apis with aah which I think is the more common usecase for Go - and therefore aah)

**Comment by joelsdc** [comment]
What do you think of just including a little one-liner script like the one you posted, maybe as an independent script in a misc/ or utils/ directory? So it's there to help, but not strictly a part of aah...

From my perspective, the `aah mkpasswd` was just a suggestion, to be honest, for me any way would work, but I have to agree with you @adelowo that this could open a door to start all sorts of requests...

**Comment by jeevatkm** [comment]
@joelsdc @adelowo Sounds good. I'm closing this issue.

There is a plan of implementing PasswordEncoder hashing method(s) for Authentication and Authorization purpose on `security/acrypto` package.

So then script can use those methods. We can document that in the documentation.
